version: '3.8'

services:
  web:
    image: akshatpareek/clientsphere-website:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8085:80"
    restart: always
    container_name: clientsphere-website
